import type { HotelData } from "@/features/hotel/types/hotel.types";

export type {
  RoomCategory,
  RoomInclusions,
  AmenityCategory,
  RoomType,
  Review,
  LandmarkCategory,
  Landmark,
  HotelImage,
  HotelFeature,
  AmenityBadge,
  ReviewCategoryScores,
  HotelPolicy,
  HotelData,
  SelectedRoomItem,
  StickyBookingBarProps,
  RoomDetailsModalProps,
  RoomCardProps,
  ReviewsSectionProps,
  GalleryModalProps,
} from "@/features/hotel/types/hotel.types";

export const BENTOTA_BEACH_DATA: HotelData = {
  id: "001",
  name: "Bentota Azure Beachfront Resort & Spa",
  starRating: 5,
  reviewScore: 9.1,
  reviewCount: 1640,
  reviewLabel: "Superb",
  address: "12 Galle Road, Bentota Peninsula",
  city: "Bentota",
  country: "Sri Lanka",
  locationHighlights: "Direct Golden Sands Access — Where the Bentota River Meets the Indian Ocean",
  heroImages: [
    {
      url: "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80",
      caption: "Lagoon-Style Beachfront Swimming Pool",
      category: "Exterior",
    },
    {
      url: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80",
      caption: "Oceanfront King Villa Bedroom",
      category: "Rooms",
    },
    {
      url: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=800&q=80",
      caption: "Open-Air Beach Bar & Seafood Grill",
      category: "Dining",
    },
    {
      url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",
      caption: "Coconut Grove Ayurvedic Spa Pavilion",
      category: "Wellness",
    },
    {
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80",
      caption: "Private Plunge Pool Cabana",
      category: "Exterior",
    },
    {
      url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
      caption: "Open-Sky Tropical Shower & Stone Tub",
      category: "Bathroom",
    },
    {
      url: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80",
      caption: "Sunset Palms Beachfront Cocktail Lounge",
      category: "Lounge",
    },
  ],
  highlights: [
    {
      icon: "Waves",
      title: "Direct Beachfront Access",
      description: "Step straight from the coconut grove onto pristine golden sands",
    },
    {
      icon: "Sparkles",
      title: "Resort Wellness Retreat",
      description: "Traditional herbal massages and daily beachfront yoga pavilions",
    },
    {
      icon: "Utensils",
      title: "Catch-of-the-Day Dining",
      description: "Fresh coastal lobster, jumbo prawns, and tropical beach barbecue",
    },
    {
      icon: "ShieldCheck",
      title: "Water Sports Certified",
      description: "Private marina on the Bentota River for jet skis, sailing, and river safaris",
    },
  ],
  description: [
    "Surrounded by swaying coconut palms between the calm waters of the Bentota River and the turquoise Indian Ocean, Bentota Azure Beachfront Resort & Spa offers a tropical seaside sanctuary.",
    "Designed in open-air tropical modernist style, the resort features private beach chalets, an expansive lagoon pool, tranquil wellness pavilions, and beachfront candlelit dining under the stars.",
    "Whether relaxing on sun loungers along the shoreline or engaging in water sports along the river lagoon, guests enjoy top-tier coastal hospitality in one of Sri Lanka's prime beach destinations.",
  ],
  topAmenities: [
    { icon: "Wifi", label: "Free High-Speed Wi-Fi" },
    { icon: "Pool", label: "Lagoon Swimming Pool" },
    { icon: "Waves", label: "Private Beach Cabanas" },
    { icon: "Utensils", label: "Beachfront Seafood Grill" },
    { icon: "Anchor", label: "Water Sports Marina" },
    { icon: "Coffee", label: "Buffet Breakfast Included" },
    { icon: "AirConditioner", label: "Climate Control AC" },
    { icon: "Clock", label: "24/7 Guest Concierge" },
  ],
  rooms: [
    {
      id: "room-ocean-chalet",
      title: "Deluxe Oceanfront Garden Chalet",
      category: "deluxe",
      pricePerNight: 130,
      originalPrice: 175,
      sizeSqM: 45,
      maxAdults: 2,
      maxChildren: 1,
      bedType: "1 Four-Poster King Bed",
      viewType: "Garden & Golden Beach View",
      images: [
        "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
      ],
      inclusions: {
        freeBreakfast: true,
        freeCancellation: true,
        cancellationDeadline: "Sep 22, 2026",
        noPrepaymentNeeded: true,
        instantConfirmation: true,
      },
      popularAmenities: [
        "Private Sand Deck",
        "Open-Sky Tropical Shower",
        "Beach Towels & Loungers",
        "Espresso Machine",
        "Free High-Speed Wi-Fi",
      ],
      allAmenities: [
        {
          category: "Chalet Living",
          items: ["45 m² Private Chalet", "Teak Sun Loungers", "In-room Digital Safe", "Soundproof Sliding Doors"],
        },
        {
          category: "Bathroom & Spa",
          items: ["Open-air Rain Shower", "Natural Coconut Bath Amenities", "Plush Bathrobes"],
        },
      ],
    },
    {
      id: "room-plunge-villa",
      title: "Royal Beach Villa with Private Plunge Pool",
      category: "suite",
      pricePerNight: 260,
      originalPrice: 350,
      sizeSqM: 75,
      maxAdults: 2,
      maxChildren: 2,
      bedType: "1 Extra-Large King Bed",
      viewType: "Direct Ocean & Sunset Panorama",
      images: [
        "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=800&q=80",
      ],
      inclusions: {
        freeBreakfast: true,
        freeCancellation: true,
        cancellationDeadline: "Sep 20, 2026",
        noPrepaymentNeeded: true,
        instantConfirmation: true,
      },
      popularAmenities: [
        "Private Plunge Pool",
        "Dedicated Butler Service",
        "Direct Beach Access Gate",
        "Free Sunset Cocktails",
        "Outdoor Jacuzzi",
      ],
      allAmenities: [
        {
          category: "Villa Highlights",
          items: ["75 m² Living Space", "Private Tiled Plunge Pool", "Outdoor Daybed Cabana", "Complimentary Minibar"],
        },
        {
          category: "Exclusive Services",
          items: ["Evening Turndown Service", "Complimentary High Tea", "Priority Water Sports Booking"],
        },
      ],
    },
    {
      id: "room-lagoon-family",
      title: "Two-Bedroom Palm Grove Family Villa",
      category: "family",
      pricePerNight: 340,
      originalPrice: 460,
      sizeSqM: 110,
      maxAdults: 4,
      maxChildren: 2,
      bedType: "1 King Bed + 2 Twin Beds",
      viewType: "Resort Lagoon Pool & Palm Gardens",
      images: [
        "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80",
      ],
      inclusions: {
        freeBreakfast: true,
        freeCancellation: true,
        cancellationDeadline: "Sep 18, 2026",
        noPrepaymentNeeded: true,
        instantConfirmation: true,
      },
      popularAmenities: [
        "2 Separate Bedrooms",
        "2 En-suite Bathrooms",
        "Spacious Living Hall",
        "Kitchenette & Dining Area",
        "Child Safety Measures",
      ],
      allAmenities: [
        {
          category: "Family Comforts",
          items: ["110 m² Private Villa", "Enclosed Tropical Courtyard", "Microwave & Refrigerator", "Smart TVs in All Rooms"],
        },
      ],
    },
  ],
  reviewCategories: {
    cleanliness: 9.3,
    location: 9.7,
    service: 9.2,
    facilities: 9.1,
    valueForMoney: 8.8,
    comfort: 9.3,
  },
  reviews: [
    {
      id: "rev-301",
      author: "Liam & Chloe Bennett",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
      country: "Australia",
      rating: 9.6,
      ratingLabel: "Exceptional",
      stayDate: "August 2026",
      roomType: "Royal Beach Villa with Private Plunge Pool",
      title: "Paradise right on the beach!",
      comment: "Walking out directly onto soft golden sand every morning was incredible. The private plunge pool in our villa was spotless and the beach seafood barbecue dinner was outstanding.",
      positivePoints: ["Direct beach access", "Spacious plunge villa", "Attentive staff"],
    },
    {
      id: "rev-302",
      author: "Nimal Ranasinghe",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
      country: "Sri Lanka",
      rating: 9.0,
      ratingLabel: "Superb",
      stayDate: "July 2026",
      roomType: "Deluxe Oceanfront Garden Chalet",
      title: "Great weekend getaway close to Colombo",
      comment: "Just over an hour's drive from Colombo along the expressway. Highly recommend the Bentota River boat safari arranged by the hotel concierge.",
      positivePoints: ["Close to expressway", "Peaceful lagoon environment"],
    },
  ],
  landmarks: [
    { name: "Bentota Golden Beach", distance: "50 m", category: "attraction" },
    { name: "Bentota River Marina & Safari", distance: "350 m", category: "attraction" },
    { name: "Brief Garden by Bevis Bawa", distance: "8.2 km", category: "attraction" },
    { name: "Bentota Railway Station", distance: "1.5 km", category: "transport" },
    { name: "Kosgoda Sea Turtle Hatchery", distance: "11.0 km", category: "attraction" },
    { name: "Bandaranaike International Airport (CMB)", distance: "108 km", category: "airport" },
  ],
  policies: [
    {
      title: "Check-in / Check-out",
      details: "Check-in begins at 14:00 PM. Check-out is until 12:00 PM. Late check-out available depending on room availability.",
    },
    {
      title: "Cancellation / Prepayment",
      details: "Free cancellation available up to 48 hours prior to arrival. Prepayment not required at the time of booking.",
    },
    {
      title: "Beach & Pool Safety",
      details: "Lifeguards are on duty at the pool and designated beachfront area from 07:00 AM to 18:30 PM daily.",
    },
    {
      title: "Water Sports Equipment",
      details: "Complimentary kayaks and paddleboards are available to registered guests upon booking through the private marina.",
    },
  ],
};



export const NUWARA_ELIYA_GRAND_DATA: HotelData = {
  id: "002",
  name: "Nuwara Eliya Highland Grand Chateau & Tea Estate",
  starRating: 5,
  reviewScore: 9.3,
  reviewCount: 1780,
  reviewLabel: "Superb",
  address: "24 Grand Hotel Road, Nuwara Eliya",
  city: "Nuwara Eliya",
  country: "Sri Lanka",
  locationHighlights: "Highland Heart — 400m from Victoria Park & Gregory Lake",
  heroImages: [
    {
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      caption: "Tudor-Style Historic Manor & Rose Gardens",
      category: "Exterior",
    },
    {
      url: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
      caption: "Victorian Fireplace Deluxe King Room",
      category: "Rooms",
    },
    {
      url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
      caption: "The Highland Oak Dining Room & Wine Bar",
      category: "Dining",
    },
    {
      url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",
      caption: "Heated Hydrotherapy Wellness Spa",
      category: "Wellness",
    },
    {
      url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
      caption: "Misty Mountain View Executive Suite",
      category: "Rooms",
    },
    {
      url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
      caption: "Marble Soaking Tub with Garden Views",
      category: "Bathroom",
    },
    {
      url: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80",
      caption: "Colonial Billiards & High Tea Lounge",
      category: "Lounge",
    },
  ],
  highlights: [
    {
      icon: "Sparkles",
      title: "Victorian Elegance",
      description: "Authentic 19th-century colonial estate with manicured rose gardens",
    },
    {
      icon: "Coffee",
      title: "Signature High Tea",
      description: "Award-winning high tea service featuring single-origin Ceylon brews",
    },
    {
      icon: "Flame",
      title: "Cozy Open Fireplaces",
      description: "Working log fireplaces in every luxury suite and social lounge",
    },
    {
      icon: "ShieldCheck",
      title: "Heritage Luxury Partner",
      description: "Rated 9.6/10 for vintage charm and bespoke butler attention",
    },
  ],
  description: [
    "Set amidst the cool misty hills of 'Little England', Nuwara Eliya Highland Grand Chateau & Tea Estate preserves the romance of colonial tea country.",
    "The estate features manicured English flower gardens, roaring log fireplaces, a heated indoor hydrotherapy pool, and high-altitude tea tastings paired with classical culinary offerings.",
    "A short stroll leads to Victoria Park, the historic golf club, and the picturesque shores of Gregory Lake, offering the premier highland retreat in Sri Lanka.",
  ],
  topAmenities: [
    { icon: "Wifi", label: "Fiber Optic Wi-Fi" },
    { icon: "Pool", label: "Indoor Heated Pool" },
    { icon: "Utensils", label: "Fine Dining Restaurant" },
    { icon: "Car", label: "Free Valet Parking" },
    { icon: "Coffee", label: "Highland Tea & Breakfast" },
    { icon: "Flame", label: "In-Room Log Fireplaces" },
    { icon: "AirConditioner", label: "Individual Heating Units" },
    { icon: "Clock", label: "24-Hour Butler Service" },
  ],
  rooms: [
    {
      id: "room-manor-king",
      title: "Vintage Manor King Room with Fireplace",
      category: "deluxe",
      pricePerNight: 135,
      originalPrice: 180,
      sizeSqM: 38,
      maxAdults: 2,
      maxChildren: 1,
      bedType: "1 Extra-Large King Bed",
      viewType: "English Rose Garden & Pine Trees",
      images: [
        "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
      ],
      inclusions: {
        freeBreakfast: true,
        freeCancellation: true,
        cancellationDeadline: "Sep 28, 2026",
        noPrepaymentNeeded: true,
        instantConfirmation: true,
      },
      popularAmenities: [
        "Wood Fireplace",
        "Garden Terrace Access",
        "Artisanal Tea Maker",
        "Heated Duvets",
        "Free High-Speed Wi-Fi",
      ],
      allAmenities: [
        {
          category: "Room Atmosphere",
          items: ["38 m² Tudor-style Room", "Working Fireplace", "Heated Carpet Flooring", "Hand-carved Mahogany Desk"],
        },
        {
          category: "Bathroom & Comfort",
          items: ["Clawfoot Bathtub", "Heated Towel Racks", "Organic Herbal Bath Soaps", "Plush Wool Slippers"],
        },
      ],
    },
    {
      id: "room-plantation-suite",
      title: "Planter's Master Suite with Panoramic Views",
      category: "suite",
      pricePerNight: 245,
      originalPrice: 330,
      sizeSqM: 64,
      maxAdults: 2,
      maxChildren: 2,
      bedType: "1 Four-Poster King Bed",
      viewType: "Pidurutalagala Mountain & Tea Estate",
      images: [
        "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
      ],
      inclusions: {
        freeBreakfast: true,
        freeCancellation: true,
        cancellationDeadline: "Sep 25, 2026",
        noPrepaymentNeeded: true,
        instantConfirmation: true,
      },
      popularAmenities: [
        "Private Sunroom Balcony",
        "Dedicated Fireplace Attendant",
        "Complimentary High Tea",
        "Marble Jacuzzi Bath",
      ],
      allAmenities: [
        {
          category: "Suite Highlights",
          items: ["64 m² Expansive Suite", "Separate Glass-encased Sunroom", "Walk-in Dressing Closet", "Fine Wine Cellar"],
        },
        {
          category: "VIP Amenities",
          items: ["Daily High Tea at the Verandah", "Evening Turn-down Hot Water Bottles", "Personal Butler Service"],
        },
      ],
    },
    {
      id: "room-chateau-family",
      title: "The Heritage Two-Bedroom Family Suite",
      category: "family",
      pricePerNight: 320,
      originalPrice: 440,
      sizeSqM: 88,
      maxAdults: 4,
      maxChildren: 2,
      bedType: "1 King Bed + 2 Single Beds",
      viewType: "Victoria Park & Manicured Lawn View",
      images: [
        "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
      ],
      inclusions: {
        freeBreakfast: true,
        freeCancellation: true,
        cancellationDeadline: "Sep 22, 2026",
        noPrepaymentNeeded: true,
        instantConfirmation: true,
      },
      popularAmenities: [
        "Two Fireplace Lounges",
        "Two En-suite Bathrooms",
        "Hot Chocolate & Marshmallow Station",
        "Board Games & Books Corner",
      ],
      allAmenities: [
        {
          category: "Family Features",
          items: ["88 m² Spacious Suite", "Interconnected Living Room", "Two En-suite Victorian Bathrooms", "Baby Cots Available"],
        },
      ],
    },
  ],
  reviewCategories: {
    cleanliness: 9.6,
    location: 9.7,
    service: 9.5,
    facilities: 9.0,
    valueForMoney: 8.8,
    comfort: 9.5,
  },
  reviews: [
    {
      id: "rev-401",
      author: "Marcus & Evelyn Ward",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
      country: "United Kingdom",
      rating: 9.7,
      ratingLabel: "Exceptional",
      stayDate: "August 2026",
      roomType: "Planter's Master Suite with Panoramic Views",
      title: "True colonial luxury in the cool highlands",
      comment: "Having real log fires lit in our room every evening was wonderful. The afternoon high tea on the lawn is easily the best in Nuwara Eliya.",
      positivePoints: ["Cozy fireplaces", "Delicious high tea", "Charming historical details"],
    },
    {
      id: "rev-402",
      author: "Ruwan Jayasuriya",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
      country: "Sri Lanka",
      rating: 9.1,
      ratingLabel: "Superb",
      stayDate: "July 2026",
      roomType: "Vintage Manor King Room with Fireplace",
      title: "Great family getaway for the holiday season",
      comment: "Superb location walking distance from Victoria Park and Gregory Lake. The staff was very attentive and the heated indoor pool was a great plus for the kids.",
      positivePoints: ["Heated pool", "Walking distance to lake and park"],
    },
  ],
  landmarks: [
    { name: "Victoria Park Nuwara Eliya", distance: "400 m", category: "attraction" },
    { name: "Gregory Lake & Water Sports", distance: "850 m", category: "attraction" },
    { name: "Nuwara Eliya Golf Club", distance: "600 m", category: "attraction" },
    { name: "Pedro Tea Estate & Factory", distance: "3.5 km", category: "attraction" },
    { name: "Nanu Oya Railway Station", distance: "8.2 km", category: "transport" },
    { name: "Horton Plains National Park", distance: "28.0 km", category: "attraction" },
  ],
  policies: [
    {
      title: "Check-in / Check-out",
      details: "Check-in from 14:00 PM. Check-out until 11:30 AM. Complimentary luggage storage and heated waiting lounge for early arrivals.",
    },
    {
      title: "Cancellation / Prepayment",
      details: "Free cancellation up to 48 hours prior to check-in. Prepayment is not required at the time of booking.",
    },
    {
      title: "Dress Code",
      details: "Smart casual attire is requested for dinner service in The Highland Oak Dining Room.",
    },
    {
      title: "Heating & Fireplace Service",
      details: "Log fires are attended and lit daily by estate staff between 17:30 PM and 21:30 PM complimentary.",
    },
  ],
};




export const ELLA_RETREAT_DATA: HotelData = {
  id: "003",
  name: "Ella Misty Peaks Nature Resort & Spa",
  starRating: 5,
  reviewScore: 9.4,
  reviewCount: 2150,
  reviewLabel: "Exceptional",
  address: "88 Waterfall Road, Ella Gap",
  city: "Ella",
  country: "Sri Lanka",
  locationHighlights: "Panoramic Mountain Ridge — Overlooking Ella Rock & Little Adam's Peak",
  heroImages: [
    {
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1200&q=80",
      caption: "Infinity Pool Suspended Over Misty Valleys",
      category: "Exterior",
    },
    {
      url: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
      caption: "Signature Panoramic Chalet Bedroom",
      category: "Rooms",
    },
    {
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
      caption: "Open-air Sunrise Mountain Dining Deck",
      category: "Dining",
    },
    {
      url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",
      caption: "Hillside Herbal Bath & Ayurveda Retreat",
      category: "Wellness",
    },
    {
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80",
      caption: "Private Plunge Pool with Valley Sunrise View",
      category: "Exterior",
    },
    {
      url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
      caption: "Glass-Front Luxury Stone Bath",
      category: "Bathroom",
    },
    {
      url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
      caption: "Fireside Tea & Cocktail Lounge",
      category: "Lounge",
    },
  ],
  highlights: [
    {
      icon: "Mountain",
      title: "Epic Valley Vistas",
      description: "Direct uninterrupted panoramas across Ella Gap and Little Adam's Peak",
    },
    {
      icon: "Sparkles",
      title: "Eco-Luxury Living",
      description: "Sustainable timber suites paired with premium five-star amenities",
    },
    {
      icon: "Coffee",
      title: "Artisanal Ceylon Teas",
      description: "Fresh high-grown teas picked from adjacent organic estates",
    },
    {
      icon: "ShieldCheck",
      title: "TripAdvisor Best of Best",
      description: "Recognized among Sri Lanka's leading boutique hill retreats",
    },
  ],
  description: [
    "Perched on the verdant edge of the Ella mountain pass, Ella Misty Peaks Nature Resort & Spa offers a tranquil escape above the clouds with panoramic ridge vistas.",
    "Engineered with eco-friendly architecture and teak interiors, each chalet opens directly onto private mountain decks. Unwind in our heated horizon pool, indulge in herbal Ayurvedic therapies, or savor artisanal farm-to-table cuisine prepared with fresh estate produce.",
    "Conveniently situated moments from Nine Arches Bridge and top hiking trails, the resort provides the ideal balance of adventurous trekking and luxury mountain serenity.",
  ],
  topAmenities: [
    { icon: "Wifi", label: "Fiber Optic Wi-Fi" },
    { icon: "Pool", label: "Heated Mountain Pool" },
    { icon: "Utensils", label: "Hilltop Restaurant & Bar" },
    { icon: "Car", label: "Free Private Parking" },
    { icon: "Plane", label: "Heli-Pad & Shuttle Service" },
    { icon: "Coffee", label: "Artisan Breakfast Included" },
    { icon: "AirConditioner", label: "Climate Control & Heating" },
    { icon: "Clock", label: "24-Hour Mountain Concierge" },
  ],
  rooms: [
    {
      id: "room-cloud-chalet",
      title: "Cloud View Timber Chalet",
      category: "deluxe",
      pricePerNight: 110,
      originalPrice: 155,
      sizeSqM: 40,
      maxAdults: 2,
      maxChildren: 1,
      bedType: "1 King Canopy Bed",
      viewType: "Ella Gap & Cloud Forest View",
      images: [
        "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
      ],
      inclusions: {
        freeBreakfast: true,
        freeCancellation: true,
        cancellationDeadline: "Sep 20, 2026",
        noPrepaymentNeeded: true,
        instantConfirmation: true,
      },
      popularAmenities: [
        "Suspended Hammock Balcony",
        "Floor-to-Ceiling Glass Views",
        "Espresso Station",
        "Rain Shower",
        "High-Speed Wi-Fi",
      ],
      allAmenities: [
        {
          category: "Chalet Living",
          items: ["40 m² Eco-Chalet", "Private Mountain Sun Terrace", "Natural Teak Floors", "In-room Safe"],
        },
        {
          category: "Bath & Wellness",
          items: ["Free-standing Stone Tub", "Herbal Bath Salts", "Organic Bamboo Toiletries"],
        },
      ],
    },
    {
      id: "room-summit-plunge-suite",
      title: "Summit Suite with Private Heated Plunge Pool",
      category: "suite",
      pricePerNight: 235,
      originalPrice: 320,
      sizeSqM: 65,
      maxAdults: 2,
      maxChildren: 1,
      bedType: "1 Extra-Large King Bed",
      viewType: "Ella Rock & Sunrise Ridge View",
      images: [
        "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=80",
      ],
      inclusions: {
        freeBreakfast: true,
        freeCancellation: true,
        cancellationDeadline: "Sep 18, 2026",
        noPrepaymentNeeded: true,
        instantConfirmation: true,
      },
      popularAmenities: [
        "Private Heated Plunge Pool",
        "Panoramic Valley Terrace",
        "Daily High Tea Service",
        "Butler Service",
      ],
      allAmenities: [
        {
          category: "Suite Highlights",
          items: ["65 m² Living Space", "Private Infinity Heated Tub", "Open-air Daybed", "Designer Fireplace"],
        },
        {
          category: "VIP Mountain Services",
          items: ["Daily Sunrise Yoga Session", "Complimentary High Tea", "Luggage Porter Service"],
        },
      ],
    },
    {
      id: "room-family-lodge",
      title: "Pine Crest Family Mountain Lodge",
      category: "family",
      pricePerNight: 310,
      originalPrice: 420,
      sizeSqM: 90,
      maxAdults: 4,
      maxChildren: 2,
      bedType: "2 King Beds + 1 Daybed",
      viewType: "Ravana Falls & Pine Forest View",
      images: [
        "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
      ],
      inclusions: {
        freeBreakfast: true,
        freeCancellation: true,
        cancellationDeadline: "Sep 15, 2026",
        noPrepaymentNeeded: true,
        instantConfirmation: true,
      },
      popularAmenities: [
        "Two En-suite Bedrooms",
        "Expansive Living Area",
        "Kid-friendly Play Corner",
        "Tea Pantry & Coffee Bar",
      ],
      allAmenities: [
        {
          category: "Lodge Layout",
          items: ["90 m² Two-Story Lodge", "Two Full Luxury Bathrooms", "Wrap-around Viewing Deck", "Board Games Library"],
        },
      ],
    },
  ],
  reviewCategories: {
    cleanliness: 9.6,
    location: 9.9,
    service: 9.5,
    facilities: 9.2,
    valueForMoney: 9.0,
    comfort: 9.5,
  },
  reviews: [
    {
      id: "rev-201",
      author: "Oliver & Emma Davies",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
      country: "United Kingdom",
      rating: 9.8,
      ratingLabel: "Exceptional",
      stayDate: "August 2026",
      roomType: "Summit Suite with Private Heated Plunge Pool",
      title: "Watching sunrise from the plunge pool is pure magic",
      comment: "Easily one of the most stunning views in Sri Lanka. The staff packed us delicious breakfast boxes for our early morning Little Adam's Peak hike. Will return for sure!",
      positivePoints: ["Heated infinity pool", "Incredible breakfast spread", "Helpful trail guides"],
    },
    {
      id: "rev-202",
      author: "Siddharth Verma",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
      country: "India",
      rating: 9.3,
      ratingLabel: "Superb",
      stayDate: "July 2026",
      roomType: "Cloud View Timber Chalet",
      title: "Quiet, peaceful and very cozy retreat",
      comment: "Very relaxing atmosphere. Watching the mist roll into the valley while having afternoon tea by the terrace fire was extraordinary.",
      positivePoints: ["Peaceful location away from town noise", "Comfortable beds"],
    },
  ],
  landmarks: [
    { name: "Nine Arches Bridge", distance: "2.1 km", category: "attraction" },
    { name: "Little Adam's Peak Trailhead", distance: "1.4 km", category: "attraction" },
    { name: "Ella Rock Hiking Path", distance: "2.8 km", category: "attraction" },
    { name: "Ravana Falls", distance: "4.5 km", category: "attraction" },
    { name: "Ella Railway Station", distance: "1.8 km", category: "transport" },
    { name: "Mattala Rajapaksa Airport (HRI)", distance: "84 km", category: "airport" },
  ],
  policies: [
    {
      title: "Check-in / Check-out",
      details: "Check-in begins at 14:00 PM. Check-out is until 11:00 AM. Luggage drop-off and welcome tea provided on early arrivals.",
    },
    {
      title: "Cancellation / Prepayment",
      details: "Free cancellation up to 72 hours prior to scheduled arrival. Late cancellations incur a 1-night charge.",
    },
    {
      title: "Guided Nature Treks",
      details: "Complimentary morning guided walks to viewpoints depart daily at 06:30 AM upon advance sign-up.",
    },
    {
      title: "Quiet Hours",
      details: "To maintain peaceful natural surroundings, quiet hours are observed across all chalets between 22:00 PM and 07:00 AM.",
    },
  ],
};





export const GALLE_HERITAGE_DATA: HotelData = {
  id: "004",
  name: "Galle Fort Heritage Villa & Ocean Suites",
  starRating: 5,
  reviewScore: 9.2,
  reviewCount: 1890,
  reviewLabel: "Exceptional",
  address: "48 Church Street, Galle Fort",
  city: "Galle",
  country: "Sri Lanka",
  locationHighlights: "Prime Heritage Fort Location — 200m from Galle Lighthouse & Ramparts",
  heroImages: [
    {
      url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
      caption: "Colonial Dutch Architecture & Courtyard Pool",
      category: "Exterior",
    },
    {
      url: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
      caption: "Ocean View Grand Heritage Suite",
      category: "Rooms",
    },
    {
      url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
      caption: "The Verandah Fine Dining Restaurant",
      category: "Dining",
    },
    {
      url: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=800&q=80",
      caption: "Holistic Ceylon Spice Spa",
      category: "Wellness",
    },
    {
      url: "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80",
      caption: "Colonial Balcony with Rampart View",
      category: "Exterior",
    },
    {
      url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
      caption: "Handcrafted Terrazzo Master Bathroom",
      category: "Bathroom",
    },
    {
      url: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80",
      caption: "Sunset Wine Cellar & Cigar Lounge",
      category: "Lounge",
    },
  ],
  highlights: [
    {
      icon: "MapPin",
      title: "UNESCO Heritage Site",
      description: "Located right inside the historic 17th-century Galle Dutch Fort",
    },
    {
      icon: "Sparkles",
      title: "Impeccable Luxury",
      description: "9.6 rating for comfort, vintage decor, and detail-oriented housekeeping",
    },
    {
      icon: "Coffee",
      title: "Artisanal Ceylon Breakfast",
      description: "Fresh coastal seafood delicacies, tropical fruits, and signature teas",
    },
    {
      icon: "ShieldCheck",
      title: "Boutique Luxury Certified",
      description: "Curated heritage retreat with personalized private butler service",
    },
  ],
  description: [
    "Step into timeless colonial luxury at Galle Fort Heritage Villa & Ocean Suites, situated in the heart of the UNESCO World Heritage listed Galle Fort.",
    "Carefully restored to preserve original Dutch-colonial architecture, the villa pairs antique teak furnishings with modern five-star comfort. Enjoy stunning views of the Indian Ocean from our rampart terrace, relax in the frangipani-lined courtyard pool, or savor fresh seafood at our open-air verandah.",
    "A brief walk connects you to historic ramparts, cobblestone shopping lanes, trendy cafes, and the iconic Galle Lighthouse, making it the ideal retreat for discerning travelers.",
  ],
  topAmenities: [
    { icon: "Wifi", label: "High-Speed Fiber Wi-Fi" },
    { icon: "Pool", label: "Private Courtyard Pool" },
    { icon: "Utensils", label: "Oceanfront Terrace Dining" },
    { icon: "Car", label: "Chauffeur & Valet Parking" },
    { icon: "Plane", label: "Luxury Airport Transfer" },
    { icon: "Coffee", label: "Gourmet Breakfast Included" },
    { icon: "AirConditioner", label: "Individual Climate Control" },
    { icon: "Clock", label: "24/7 Dedicated Butler Service" },
  ],
  rooms: [
    {
      id: "room-heritage-king",
      title: "Colonial King Suite with Rampart View",
      category: "deluxe",
      pricePerNight: 120,
      originalPrice: 165,
      sizeSqM: 42,
      maxAdults: 2,
      maxChildren: 1,
      bedType: "1 Four-Poster King Bed",
      viewType: "Historic Fort Ramparts & Courtyard",
      images: [
        "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
      ],
      inclusions: {
        freeBreakfast: true,
        freeCancellation: true,
        cancellationDeadline: "Sep 15, 2026",
        noPrepaymentNeeded: true,
        instantConfirmation: true,
      },
      popularAmenities: [
        "Private Verandah",
        "Antique Four-Poster Bed",
        "Nespresso Coffee Station",
        "Freestanding Bathtub",
        "High-Speed Wi-Fi",
        "Silent Inverter AC",
      ],
      allAmenities: [
        {
          category: "Heritage Details",
          items: ["42 m² High-Ceiling Suite", "Dutch Tile Flooring", "Antique Teak Wardrobe", "Handmade Brass Fixtures"],
        },
        {
          category: "Bathroom & Spa",
          items: ["Clawfoot Soaking Tub", "Rainfall Brass Shower", "Ayurvedic Luxury Bath Botanicals", "Waffle Weave Robes"],
        },
      ],
    },
    {
      id: "room-ocean-villa-suite",
      title: "Grand Ocean Panorama Suite",
      category: "suite",
      pricePerNight: 210,
      originalPrice: 290,
      sizeSqM: 68,
      maxAdults: 2,
      maxChildren: 2,
      bedType: "1 Master King Bed + Daybed",
      viewType: "Panoramic Indian Ocean & Sunset View",
      images: [
        "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
      ],
      inclusions: {
        freeBreakfast: true,
        freeCancellation: true,
        cancellationDeadline: "Sep 12, 2026",
        noPrepaymentNeeded: true,
        instantConfirmation: true,
      },
      popularAmenities: [
        "Private Oceanview Sundeck",
        "Daily Sunset Cocktail Hour",
        "Private Butler Service",
        "Jacuzzi Bath",
        "Complimentary High Tea",
      ],
      allAmenities: [
        {
          category: "Suite Highlights",
          items: ["68 m² Living Space", "Private Sea-facing Balcony", "Walk-in Dressing Room", "Curated Minibar"],
        },
        {
          category: "VIP Perks",
          items: ["Personal Butler Service", "Unpacking & Ironing Service", "Complimentary High Tea Daily"],
        },
      ],
    },
    {
      id: "room-residence-family",
      title: "The Governor's Two-Bedroom Family Residence",
      category: "family",
      pricePerNight: 285,
      originalPrice: 380,
      sizeSqM: 95,
      maxAdults: 4,
      maxChildren: 2,
      bedType: "1 Master King Bed + 2 Queen Beds",
      viewType: "Private Garden & Fort Lane View",
      images: [
        "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
      ],
      inclusions: {
        freeBreakfast: true,
        freeCancellation: true,
        cancellationDeadline: "Sep 10, 2026",
        noPrepaymentNeeded: true,
        instantConfirmation: true,
      },
      popularAmenities: [
        "Two En-suite Bedrooms",
        "Full Heritage Living Hall",
        "Private Plunge Pool Access",
        "Kitchenette & Dining Area",
      ],
      allAmenities: [
        {
          category: "Family Features",
          items: ["95 m² Heritage Residence", "Dual Master Bedrooms", "Custom Lounge Area", "Interconnecting Terraces"],
        },
      ],
    },
  ],
  reviewCategories: {
    cleanliness: 9.5,
    location: 9.8,
    service: 9.4,
    facilities: 9.0,
    valueForMoney: 8.9,
    comfort: 9.4,
  },
  reviews: [
    {
      id: "rev-101",
      author: "Julian & Clara Schmidt",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
      country: "Germany",
      rating: 9.8,
      ratingLabel: "Exceptional",
      stayDate: "August 2026",
      roomType: "Colonial King Suite with Rampart View",
      title: "An unforgettable colonial hideaway in the fort",
      comment: "The atmosphere takes you back in time while keeping every modern comfort. Having tea on the balcony watching the sunset over the fort ramparts was the highlight of our trip.",
      positivePoints: ["Unbeatable fort location", "Authentic colonial design", "Incredible service"],
    },
    {
      id: "rev-102",
      author: "Samantha Lee",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
      country: "Australia",
      rating: 9.4,
      ratingLabel: "Superb",
      stayDate: "July 2026",
      roomType: "Grand Ocean Panorama Suite",
      title: "Pure relaxation and outstanding food",
      comment: "The seafood curry at the verandah was among the best we had in Sri Lanka. The room was pristine, quiet, and very spacious.",
      positivePoints: ["Delicious food", "Courtyard pool tranquility"],
    },
  ],
  landmarks: [
    { name: "Galle Dutch Fort Ramparts", distance: "100 m", category: "attraction" },
    { name: "Galle Lighthouse", distance: "250 m", category: "attraction" },
    { name: "Dutch Reformed Church", distance: "300 m", category: "attraction" },
    { name: "Galle Railway Station", distance: "1.1 km", category: "transport" },
    { name: "Unawatuna Beach", distance: "5.8 km", category: "attraction" },
    { name: "Bandaranaike International Airport (CMB)", distance: "152 km", category: "airport" },
  ],
  policies: [
    {
      title: "Check-in / Check-out",
      details: "Check-in from 14:00 PM. Check-out until 11:30 AM. Complimentary luggage holding and early check-in upon request.",
    },
    {
      title: "Cancellation / Prepayment",
      details: "Free cancellation available up to 48 hours prior to arrival for flexible rates.",
    },
    {
      title: "Children & Extra Beds",
      details: "Children of all ages welcome. Baby cots are provided complimentary upon request.",
    },
    {
      title: "Heritage Preservation Policy",
      details: "Smoking is strictly restricted to open-air garden terraces to protect timber structures.",
    },
  ],
};




export const KANDY_HOTEL_DATA: HotelData = {
  id: "005",
  name: "Kandy City Stay & Luxury Suites asdadsda",
  starRating: 4,
  reviewScore: 8.8,
  reviewCount: 1420,
  reviewLabel: "Superb",
  address: "123 Rajapihilla Mawatha, Kandy City Center",
  city: "Kandy",
  country: "Sri Lanka",
  locationHighlights: "Prime City Location — 500m from Temple of the Sacred Tooth Relic",
  heroImages: [
    {
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      caption: "Luxury Exterior & Infinity Pool View",
      category: "Exterior",
    },
    {
      url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
      caption: "Grand Master King Suite Bedroom",
      category: "Rooms",
    },
    {
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
      caption: "Rooftop Restaurant & Panoramic Lake View",
      category: "Dining",
    },
    {
      url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",
      caption: "Serene Spa & Ayurvedic Wellness Center",
      category: "Wellness",
    },
    {
      url: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80",
      caption: "Deluxe Twin Room with Mountain View Balcony",
      category: "Rooms",
    },
    {
      url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=800&q=80",
      caption: "Modern Marble Bathroom with Rain Shower",
      category: "Bathroom",
    },
    {
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
      caption: "Executive Lounge & Evening Cocktail Lounge",
      category: "Lounge",
    },
     {
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
      caption: "Executive Lounge & Evening Cocktail Lounge",
      category: "Lounge",
    },
     {
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
      caption: "Executive Lounge & Evening Cocktail Lounge",
      category: "Lounge",
    },
  ],
  highlights: [
    {
      icon: "MapPin",
      title: "Top Rated Location",
      description: "Rated 9.5/10 by recent guests for central walking distance",
    },
    {
      icon: "Sparkles",
      title: "Sparkling Clean",
      description: "9.2 Cleanliness rating based on verified guest checks",
    },
    {
      icon: "Coffee",
      title: "Exceptional Breakfast",
      description: "Buffet with Sri Lankan specialties & International dishes",
    },
    {
      icon: "ShieldCheck",
      title: "Agoda Preferred Partner",
      description: "Guaranteed best rates & trusted hospitality partner",
    },
  ],
  description: [
    "Nestled in the lush hills surrounding the UNESCO World Heritage city of Kandy, Kandy City Stay & Luxury Suites offers an unforgettable blend of authentic Sri Lankan hospitality and modern luxury elegance.",
    "Located just a 5-minute stroll from Kandy Lake and the sacred Temple of the Tooth, our hotel features panoramic mountain-view balconies, an outdoor infinity pool, a world-class Ayurvedic spa, and fine dining serving both local delicacies and international cuisine.",
    "Whether you are visiting for a romantic getaway, family vacation, or cultural tour of Sri Lanka's hill capital, our spacious air-conditioned suites provide the ultimate sanctuary with high-speed Wi-Fi, plush bedding, and dedicated 24/7 concierge service.",
  ],
  topAmenities: [
    { icon: "Wifi", label: "Free High-Speed Wi-Fi" },
    { icon: "Pool", label: "Outdoor Infinity Pool" },
    { icon: "Utensils", label: "Rooftop Restaurant & Bar" },
    { icon: "Car", label: "Free Valet Parking" },
    { icon: "Plane", label: "Airport Shuttle Service" },
    { icon: "Coffee", label: "Free Breakfast Available" },
    { icon: "AirConditioner", label: "Full Climate Control AC" },
    { icon: "Clock", label: "24-Hour Front Desk" },
  ],
  rooms: [
    {
      id: "room-deluxe-king",
      title: "Deluxe King Room with Mountain View",
      category: "deluxe",
      pricePerNight: 85,
      originalPrice: 120,
      sizeSqM: 36,
      maxAdults: 2,
      maxChildren: 1,
      bedType: "1 Extra-Large King Bed",
      viewType: "Kandy Hills & Garden View",
      images: [
        "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80",
      ],
      inclusions: {
        freeBreakfast: true,
        freeCancellation: true,
        cancellationDeadline: "Sep 1, 2026",
        noPrepaymentNeeded: true,
        instantConfirmation: true,
      },
      popularAmenities: [
        "Private Balcony",
        "Flat-screen Smart TV",
        "Coffee/Tea Maker",
        "Rain Shower",
        "Free High-speed Wi-Fi",
        "Air Conditioning",
      ],
      allAmenities: [
        {
          category: "Room Features",
          items: ["36 m² Floor Space", "Soundproof Walls", "Hardwood/Parquet Floors", "Work Desk & Ergonomic Chair", "In-room Safe Box"],
        },
        {
          category: "Bathroom & Toiletries",
          items: ["Private Marble Bathroom", "Rain Shower", "Free Premium Toiletries", "Hairdryer", "Bathrobes & Soft Slippers"],
        },
        {
          category: "Media & Technology",
          items: ["55-inch 4K Smart TV", "Satellite Channels", "High-speed Wi-Fi", "USB Charging Ports"],
        },
        {
          category: "Food & Refreshment",
          items: ["Mini Bar", "Espresso Machine", "Complimentary Bottled Water Daily", "Electric Kettle"],
        },
      ],
    },
    {
      id: "room-executive-suite",
      title: "Executive Suite with Lake & Mountain View",
      category: "suite",
      pricePerNight: 145,
      originalPrice: 210,
      sizeSqM: 58,
      maxAdults: 2,
      maxChildren: 2,
      bedType: "1 Super-King Bed + Sofa Bed",
      viewType: "Panoramic Kandy Lake & City View",
      images: [
        "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
      ],
      inclusions: {
        freeBreakfast: true,
        freeCancellation: true,
        cancellationDeadline: "Aug 31, 2026",
        noPrepaymentNeeded: true,
        instantConfirmation: true,
      },
      popularAmenities: [
        "Executive Lounge Access",
        "Private Terrace Balcony",
        "Deep Soaking Bathtub",
        "Free Cocktail Hours",
        "Espresso Machine",
      ],
      allAmenities: [
        {
          category: "Room Features",
          items: ["58 m² Living Area", "Separate Living Room Sofa Area", "Walk-in Closet", "Panoramic Floor-to-Ceiling Windows"],
        },
        {
          category: "Bathroom & Spa",
          items: ["Deep Soaking Jacuzzi Tub", "Separate Glass Rain Shower", "Double Vanity Sinks", "Designer Luxury Toiletries"],
        },
        {
          category: "VIP Privileges",
          items: ["Complimentary Evening Cocktails", "Priority Check-in/out", "Free Airport Transfer (One Way)"],
        },
      ],
    },
    {
      id: "room-family-suite",
      title: "Grand Family Two-Bedroom Suite",
      category: "family",
      pricePerNight: 195,
      originalPrice: 280,
      sizeSqM: 82,
      maxAdults: 4,
      maxChildren: 2,
      bedType: "1 King Bed + 2 Twin Beds",
      viewType: "Pool & Tropical Garden View",
      images: [
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=800&q=80",
      ],
      inclusions: {
        freeBreakfast: true,
        freeCancellation: true,
        cancellationDeadline: "Aug 30, 2026",
        noPrepaymentNeeded: true,
        instantConfirmation: true,
      },
      popularAmenities: [
        "2 Separate Bedrooms",
        "2 En-suite Bathrooms",
        "Dining Table & Lounge Area",
        "Kitchenette with Microwave",
        "Children's Play Amenities",
      ],
      allAmenities: [
        {
          category: "Family Features",
          items: ["82 m² Spacious Suite", "Connecting Bedrooms", "Full Kitchenette & Refrigerator", "4-Seater Dining Area"],
        },
        {
          category: "Entertainment & Comfort",
          items: ["Two 55-inch Smart TVs", "PlayStation 5 Console (On Request)", "Child Safety Socket Covers"],
        },
      ],
    },
    {
      id: "room-superior-twin",
      title: "Superior Twin Room with Garden View",
      category: "deluxe",
      pricePerNight: 72,
      originalPrice: 98,
      sizeSqM: 32,
      maxAdults: 2,
      maxChildren: 1,
      bedType: "2 Single Twin Beds",
      viewType: "Courtyard & Garden View",
      images: [
        "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
      ],
      inclusions: {
        freeBreakfast: true,
        freeCancellation: true,
        cancellationDeadline: "Sep 2, 2026",
        noPrepaymentNeeded: true,
        instantConfirmation: true,
      },
      popularAmenities: [
        "Garden Terrace Access",
        "Work Station Desk",
        "Free High-speed Wi-Fi",
        "Air Conditioning",
      ],
      allAmenities: [
        {
          category: "Room Features",
          items: ["32 m² Cozy Space", "Twin Pillowtop Beds", "Air Conditioning", "Coffee Maker"],
        },
      ],
    },
  ],
  reviewCategories: {
    cleanliness: 9.2,
    location: 9.5,
    service: 9.0,
    facilities: 8.7,
    valueForMoney: 8.6,
    comfort: 9.1,
  },
  reviews: [
    {
      id: "rev-1",
      author: "David & Sarah Walker",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
      country: "United Kingdom",
      rating: 9.6,
      ratingLabel: "Exceptional",
      stayDate: "August 2026",
      roomType: "Deluxe King Room with Mountain View",
      title: "Outstanding stay in the heart of Kandy!",
      comment: "The mountain view from our balcony was breathtaking. Staff went above and beyond to organize our train tickets to Ella and recommended an amazing local tea tour. Breakfast spread was huge!",
      positivePoints: ["Unbeatable city location", "Super clean rooms", "Friendly concierge desk"],
    },
    {
      id: "rev-2",
      author: "Kasun Perera",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
      country: "Sri Lanka",
      rating: 9.2,
      ratingLabel: "Superb",
      stayDate: "July 2026",
      roomType: "Executive Suite with Lake View",
      title: "Luxury experience with incredible lake views",
      comment: "Stayed here for our wedding anniversary. The executive lounge cocktails were great, and the infinity pool overlooking Kandy Lake is world class. Will definitely return!",
      positivePoints: ["Infinity pool view", "Delicious Sri Lankan hopper breakfast"],
    },
    {
      id: "rev-3",
      author: "Elena Rostova",
      avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80",
      country: "Germany",
      rating: 8.8,
      ratingLabel: "Fabulous",
      stayDate: "August 2026",
      roomType: "Grand Family Two-Bedroom Suite",
      title: "Great family stay close to Temple of Tooth",
      comment: "Spacious rooms for 4 adults and 2 children. Very short walk to the Temple of the Tooth Relic and Kandy Lake. Kids loved the pool!",
      positivePoints: ["Spacious suite", "Great location for sightseeing"],
    },
  ],
  landmarks: [
    { name: "Kandy Lake & Promenade", distance: "300 m", category: "attraction" },
    { name: "Temple of the Sacred Tooth Relic (Sri Dalada Maligawa)", distance: "500 m", category: "attraction" },
    { name: "Kandy City Centre Shopping Mall", distance: "650 m", category: "attraction" },
    { name: "Kandy Railway Station", distance: "1.2 km", category: "transport" },
    { name: "Royal Botanical Gardens, Peradeniya", distance: "5.5 km", category: "attraction" },
    { name: "Bandaranaike International Airport (CMB)", distance: "102 km", category: "airport" },
  ],
  policies: [
    {
      title: "Check-in / Check-out",
      details: "Check-in from 14:00 PM anytime. Check-out until 12:00 PM. Early check-in or late check-out available upon request subject to availability.",
    },
    {
      title: "Cancellation / Prepayment",
      details: "Cancellation and prepayment policies vary according to accommodation type. Free cancellation available up to 24-48 hours before check-in on most room types.",
    },
    {
      title: "Children & Extra Beds",
      details: "Children of any age are welcome. Children aged 6 and above are considered adults at this property. Extra beds can be requested for $25 per night.",
    },
    {
      title: "Pets",
      details: "Pets are not allowed on the property premises, except for registered service animals.",
    },
  ],
};

export const ALL_HOTELS: HotelData[] = [
  KANDY_HOTEL_DATA,
  BENTOTA_BEACH_DATA,
  NUWARA_ELIYA_GRAND_DATA,
  ELLA_RETREAT_DATA,
  GALLE_HERITAGE_DATA,
];

export function getHotelById(id?: string | null): HotelData {
  if (!id) return KANDY_HOTEL_DATA;
  const found = ALL_HOTELS.find((h) => h.id.toLowerCase() === id.toLowerCase());
  return found || KANDY_HOTEL_DATA;
}
